services:
  backend:
    build: ./
    ports:
      - 8080:8080
      - 5555:5555
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=anthologia
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
