services:
  backend:
    container_name: anthologia-api
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=${NETWORK_DATABASE_URL}
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: 'npx prisma migrate status'
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    container_name: anthologia-db
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - PGUSER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_volume:/var/lib/postgresql/data/
    healthcheck:
      test: 'pg_isready -d $DB_NAME -U $DB_USER'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

networks:
  backend_network:
  database_network:

volumes:
  database_volume:
