services:
  backend:
    build: ./
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
      - POSTGRES_DB=anthologia
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
